import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '../context/theme-provider';
import { Toaster } from '../components/ui/toaster';
import { DM_Sans } from 'next/font/google';
import QueryProvider from '../context/query-provider';

export const metadata: Metadata = {
  title: 'Secure-Auth',
  description: 'Generated by create next app',
};

const dm_sans = DM_Sans({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-background ${dm_sans.className} antialiased`}>
        <QueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem={false}
            disableTransitionOnChange
          >
            {children}
            <Toaster />
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
